# SPDX-License-Identifier: MPL-2.0
# (MPL-2.0 preferred; MPL-2.0 required for Julia ecosystem)
# Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
#
# ZeroProb.jl Backend Abstraction (self-contained)
#
# This layer previously delegated to AcceleratorGate.jl for the shared
# coprocessor type hierarchy and the self-healing hook generator. AcceleratorGate
# is an unregistered placeholder package (UUID 59f742c7) that is not in the Julia
# General registry; it broke `Pkg.instantiate()` and was removed from Project.toml
# on 2026-06-14 (mirrors the sibling .jl dependency-hygiene fix).
#
# The base package's core (notably src/measures.jl) consumes only a small backend
# surface: `current_backend`, `JuliaBackend`, and the five `backend_*` entry
# points. That surface is defined locally here so the pure-Julia code path is
# fully self-contained and precompiles with no external accelerator dependency.
#
# The optional GPU/coprocessor extensions in ext/ still reference AcceleratorGate
# and therefore only load when a real accelerator package supplies those symbols;
# they are not exercised by the test suite (test target = Test/Random/LinearAlgebra).

# ============================================================================
# Backend type hierarchy (local; formerly imported from AcceleratorGate)
# ============================================================================

"""Abstract supertype for all ZeroProb compute backends."""
abstract type AbstractBackend end

"""Pure-Julia reference backend. The default; always available."""
struct JuliaBackend <: AbstractBackend end

"""Supertype for GPU backends (CUDA/Metal/ROCm), supplied by the ext/ extensions."""
abstract type GPUBackend <: AbstractBackend end

"""Supertype for coprocessor backends (TPU/NPU/FPGA/…), supplied by ext/ extensions."""
abstract type CoprocessorBackend <: AbstractBackend end

"""
    current_backend() -> AbstractBackend

Return the active compute backend. With no accelerator extension loaded this is
always `JuliaBackend()`, so every core algorithm runs on the pure-Julia path.
Accelerator extensions may override this to switch the active backend.
"""
current_backend() = JuliaBackend()

# ============================================================================
# Domain-Specific Operation Hooks -- ZeroProb
# ============================================================================

# Julia fallback implementations (return `nothing` => caller uses pure-Julia path)
backend_probability_eval(::JuliaBackend, args...) = nothing
backend_bayesian_update(::JuliaBackend, args...) = nothing
backend_log_likelihood(::JuliaBackend, args...) = nothing
backend_sampling(::JuliaBackend, args...) = nothing
backend_marginalize(::JuliaBackend, args...) = nothing

# Coprocessor extension hooks (concrete extensions overload these)
function backend_coprocessor_probability_eval end
function backend_coprocessor_bayesian_update end
function backend_coprocessor_log_likelihood end
function backend_coprocessor_sampling end
function backend_coprocessor_marginalize end

# Self-healing fallbacks: any coprocessor hook with no extension-provided method
# falls back to the pure-Julia implementation. Formerly generated by
# AcceleratorGate.generate_self_healing_hooks; inlined here so the base package
# is closed under its own dependencies.
backend_coprocessor_probability_eval(::CoprocessorBackend, args...) = backend_probability_eval(JuliaBackend(), args...)
backend_coprocessor_bayesian_update(::CoprocessorBackend, args...)  = backend_bayesian_update(JuliaBackend(), args...)
backend_coprocessor_log_likelihood(::CoprocessorBackend, args...)   = backend_log_likelihood(JuliaBackend(), args...)
backend_coprocessor_sampling(::CoprocessorBackend, args...)         = backend_sampling(JuliaBackend(), args...)
backend_coprocessor_marginalize(::CoprocessorBackend, args...)      = backend_marginalize(JuliaBackend(), args...)

# Dispatch: CoprocessorBackend -> coprocessor hook
backend_probability_eval(b::CoprocessorBackend, args...) = backend_coprocessor_probability_eval(b, args...)
backend_bayesian_update(b::CoprocessorBackend, args...) = backend_coprocessor_bayesian_update(b, args...)
backend_log_likelihood(b::CoprocessorBackend, args...) = backend_coprocessor_log_likelihood(b, args...)
backend_sampling(b::CoprocessorBackend, args...) = backend_coprocessor_sampling(b, args...)
backend_marginalize(b::CoprocessorBackend, args...) = backend_coprocessor_marginalize(b, args...)

# Dispatch: GPUBackend -> Julia fallback (extensions override per-device)
backend_probability_eval(b::GPUBackend, args...) = backend_probability_eval(JuliaBackend(), args...)
backend_bayesian_update(b::GPUBackend, args...) = backend_bayesian_update(JuliaBackend(), args...)
backend_log_likelihood(b::GPUBackend, args...) = backend_log_likelihood(JuliaBackend(), args...)
backend_sampling(b::GPUBackend, args...) = backend_sampling(JuliaBackend(), args...)
backend_marginalize(b::GPUBackend, args...) = backend_marginalize(JuliaBackend(), args...)
